import React, { useMemo } from 'react';
const imageLinks = [
  "https://www.pizzaexpress.vn/wp-content/uploads/2018/08/shutterstock_657998458-780x490.jpg",
  "https://i.ytimg.com/vi/JEPtJvykQkI/maxresdefault.jpg",
  "https://www.allrecipes.com/thmb/5JVfA7MxfTUPfRerQMdF-nGKsLY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25473-the-perfect-basic-burger-DDMFS-4x3-56eaba3833fd4a26a82755bcd0be0c54.jpg",
  "https://annajones.imgix.net/recipes/the-really-hungry-burger/Really_hungry_burger_for_web.jpg?w=3072&h=3994",
];

// Hàm chọn 3 hình ảnh ngẫu nhiên và trả về dưới dạng các thuộc tính Image1, Image2, Image3
function getRandomImages() {
  const shuffled = [...imageLinks].sort(() => 0.5 - Math.random());
  return {
    Image1: shuffled[0],
    Image2: shuffled[1],
    Image3: shuffled[2],
  };
}

export const foods = [
  {
    FoodId: 1,
    Name: "Pizza",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 10,
    Rating: 4.5,
    NumberRating: 120,
    Price: 15000,
    Description: "Delicious Italian pizza with fresh ingredients.",
    ...getRandomImages(),
  },
  {
    FoodId: 2,
    Name: "Sushi",
    FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
    ItemLeft: 5,
    Rating: 4.8,
    NumberRating: 200,
    Price: 20000,
    Description: "Authentic Japanese sushi, made with premium fish.",
    ...getRandomImages(),
  },
  {
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
  {
    FoodId: 1,
    Name: "Pizza",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 10,
    Rating: 4.5,
    NumberRating: 120,
    Price: 15000,
    Description: "Delicious Italian pizza with fresh ingredients.",
    ...getRandomImages(),
  },
  {
    FoodId: 2,
    Name: "Sushi",
    FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
    ItemLeft: 5,
    Rating: 4.8,
    NumberRating: 200,
    Price: 20000,
    Description: "Authentic Japanese sushi, made with premium fish.",
    ...getRandomImages(),
  },
  {
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
  {
    FoodId: 1,
    Name: "Pizza",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 10,
    Rating: 4.5,
    NumberRating: 120,
    Price: 15000,
    Description: "Delicious Italian pizza with fresh ingredients.",
    ...getRandomImages(),
  },
  {
    FoodId: 2,
    Name: "Sushi",
    FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
    ItemLeft: 5,
    Rating: 4.8,
    NumberRating: 200,
    Price: 20000,
    Description: "Authentic Japanese sushi, made with premium fish.",
    ...getRandomImages(),
  },
  {
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
  {
    FoodId: 1,
    Name: "Pizza",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 10,
    Rating: 4.5,
    NumberRating: 120,
    Price: 15000,
    Description: "Delicious Italian pizza with fresh ingredients.",
    ...getRandomImages(),
  },
  {
    FoodId: 2,
    Name: "Sushi",
    FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
    ItemLeft: 5,
    Rating: 4.8,
    NumberRating: 200,
    Price: 20000,
    Description: "Authentic Japanese sushi, made with premium fish.",
    ...getRandomImages(),
  },
  {
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
];
export const food={
  FoodId: 1,
  Name: "Pizza",
  FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
  ItemLeft: 10,
  Rating: 4.5,
  NumberRating: 120,
  Price: 15000,
  Description: "Delicious Italian pizza with fresh ingredients.",
  ...getRandomImages(),
}

  

  export const types =[
      { TypeId: 1, NameType: "Italian", ParentId: null,Foods:[
        {
          FoodId: 1,
          Name: "Pizza",
          FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
          ItemLeft: 10,
          Rating: 4.5,
          NumberRating: 120,
          Price: 15000,
          Description: "Delicious Italian pizza with fresh ingredients.",
          ...getRandomImages(),
        },
        {
          FoodId: 2,
          Name: "Sushi",
          FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
          ItemLeft: 5,
          Rating: 4.8,
          NumberRating: 200,
          Price: 20000,
          Description: "Authentic Japanese sushi, made with premium fish.",
          ...getRandomImages(),
        },
        {
          FoodId: 3,
          Name: "Burger",
          FoodType: { TypeId: 3, NameType: "American", ParentId: null },
          ItemLeft: 3,
          Rating: 4.2,
          NumberRating: 85,
          Price: 12000,
          Description: "Juicy American burger with fresh toppings.",
          ...getRandomImages(),
        },
        {
          FoodId: 4,
          Name: "Pasta",
          FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
          ItemLeft: 8,
          Rating: 4.6,
          NumberRating: 150,
          Price: 18000,
          Description: "Traditional Italian pasta with a rich sauce.",
          ...getRandomImages(),
        },] },
  { TypeId: 2, NameType: "Japanese", ParentId: 3,Foods:[{
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
], },
  { TypeId: 3, NameType: "American", ParentId: null,Foods:[
    {
      FoodId: 1,
      Name: "Pizza",
      FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
      ItemLeft: 10,
      Rating: 4.5,
      NumberRating: 120,
      Price: 15000,
      Description: "Delicious Italian pizza with fresh ingredients.",
      ...getRandomImages(),
    },
    {
      FoodId: 2,
      Name: "Sushi",
      FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
      ItemLeft: 5,
      Rating: 4.8,
      NumberRating: 200,
      Price: 20000,
      Description: "Authentic Japanese sushi, made with premium fish.",
      ...getRandomImages(),
    },
    {
      FoodId: 3,
      Name: "Burger",
      FoodType: { TypeId: 3, NameType: "American", ParentId: null },
      ItemLeft: 3,
      Rating: 4.2,
      NumberRating: 85,
      Price: 12000,
      Description: "Juicy American burger with fresh toppings.",
      ...getRandomImages(),
    },
    {
      FoodId: 4,
      Name: "Pasta",
      FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
      ItemLeft: 8,
      Rating: 4.6,
      NumberRating: 150,
      Price: 18000,
      Description: "Traditional Italian pasta with a rich sauce.",
      ...getRandomImages(),
    },] },
  { TypeId: 4, NameType: "Mexican", ParentId: 3,Foods:[
    {
      FoodId: 1,
      Name: "Pizza",
      FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
      ItemLeft: 10,
      Rating: 4.5,
      NumberRating: 120,
      Price: 15000,
      Description: "Delicious Italian pizza with fresh ingredients.",
      ...getRandomImages(),
    },
    {
      FoodId: 2,
      Name: "Sushi",
      FoodType: { TypeId: 2, NameType: "Japanese", ParentId: 3 },
      ItemLeft: 5,
      Rating: 4.8,
      NumberRating: 200,
      Price: 20000,
      Description: "Authentic Japanese sushi, made with premium fish.",
      ...getRandomImages(),
    },
    {
      FoodId: 3,
      Name: "Burger",
      FoodType: { TypeId: 3, NameType: "American", ParentId: null },
      ItemLeft: 3,
      Rating: 4.2,
      NumberRating: 85,
      Price: 12000,
      Description: "Juicy American burger with fresh toppings.",
      ...getRandomImages(),
    },
    {
      FoodId: 4,
      Name: "Pasta",
      FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
      ItemLeft: 8,
      Rating: 4.6,
      NumberRating: 150,
      Price: 18000,
      Description: "Traditional Italian pasta with a rich sauce.",
      ...getRandomImages(),
    },] },
  { TypeId: 5, NameType: "Chinese", ParentId: null,Foods:[{
    FoodId: 3,
    Name: "Burger",
    FoodType: { TypeId: 3, NameType: "American", ParentId: null },
    ItemLeft: 3,
    Rating: 4.2,
    NumberRating: 85,
    Price: 12000,
    Description: "Juicy American burger with fresh toppings.",
    ...getRandomImages(),
  },
  {
    FoodId: 4,
    Name: "Pasta",
    FoodType: { TypeId: 1, NameType: "Italian", ParentId: null },
    ItemLeft: 8,
    Rating: 4.6,
    NumberRating: 150,
    Price: 18000,
    Description: "Traditional Italian pasta with a rich sauce.",
    ...getRandomImages(),
  },
  {
    FoodId: 5,
    Name: "Taco",
    FoodType: { TypeId: 4, NameType: "Mexican", ParentId: 3 },
    ItemLeft: 12,
    Rating: 4.4,
    NumberRating: 95,
    Price: 17000,
    Description: "Mexican taco with spicy, flavorful filling.",
    ...getRandomImages(),
  },
], },
     
    ]
  ;
  export const reviews = [
    { FoodId: 1, Content: 'Delicious and fresh!', RatingValue: 4.5, Reply: 'Thank you!', User:{Username:"hahaha"} },
    { FoodId: 2, Content: 'Not too great', RatingValue: 3.0, Reply: 'Sorry to hear that.', User:{Username:"hahaha"} },
    { FoodId: 3, Content: 'Will order again', RatingValue: 5.0, Reply: 'Looking forward to it!', User:{Username:"hahaha"} },
    { FoodId: 1, Content: 'Delicious and fresh!', RatingValue: 4.5, Reply: 'Thank you!' , User:{Username:"hahaha"}},
    { FoodId: 2, Content: 'Not too great', RatingValue: 3.0, Reply: 'Sorry to hear that.' , User:{Username:"hahaha"}},
    { FoodId: 3, Content: 'Will order again', RatingValue: 5.0, Reply: 'Looking forward to it!' , User:{Username:"hahaha"}},
    { FoodId: 1, Content: 'Delicious and fresh!', RatingValue: 4.5, Reply: 'Thank you!' , User:{Username:"hahaha"}},
    { FoodId: 2, Content: 'Not too great', RatingValue: 3.0, Reply: 'Sorry to hear that.' , User:{Username:"hahaha"}},
    { FoodId: 3, Content: 'Will order again', RatingValue: 5.0, Reply: 'Looking forward to it!', User:{Username:"hahaha"} },
    { FoodId: 1, Content: 'Delicious and fresh!', RatingValue: 4.5, Reply: 'Thank you!', User:{Username:"hahaha"}},
    { FoodId: 2, Content: 'Not too great', RatingValue: 3.0, Reply: 'Sorry to hear that.' , User:{Username:"hahaha"}},
    { FoodId: 3, Content: 'Will order again', RatingValue: 5.0, Reply: 'Looking forward to it!' , User:{Username:"hahaha"}},
    // Thêm các dòng dữ liệu khác nếu cần
  ];